language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - release
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("GeoStats"); Pkg.test("GeoStats"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("GeoStats")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
